//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrayCommandStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        internal TrayCommandStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    resourceMan = new System.Resources.ResourceManager("Aspire.Cli.Resources.TrayCommandStrings", typeof(TrayCommandStrings).Assembly);
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        public static string StartDescription {
            get {
                return ResourceManager.GetString("StartDescription", resourceCulture);
            }
        }

        public static string StopDescription {
            get {
                return ResourceManager.GetString("StopDescription", resourceCulture);
            }
        }

        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }

        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }

        public static string UnsupportedPlatform {
            get {
                return ResourceManager.GetString("UnsupportedPlatform", resourceCulture);
            }
        }

        public static string NativeCliRequired {
            get {
                return ResourceManager.GetString("NativeCliRequired", resourceCulture);
            }
        }

        public static string BundleRequired {
            get {
                return ResourceManager.GetString("BundleRequired", resourceCulture);
            }
        }

        public static string PayloadMissing {
            get {
                return ResourceManager.GetString("PayloadMissing", resourceCulture);
            }
        }

        public static string HelperFailed {
            get {
                return ResourceManager.GetString("HelperFailed", resourceCulture);
            }
        }

        public static string HelperTimedOut {
            get {
                return ResourceManager.GetString("HelperTimedOut", resourceCulture);
            }
        }

        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
    }
}
