// This script runs inside a Docker build stage during publish mode. The Aspire hosting
// integration copies it into the project's obj/ folder and invokes it in a Dockerfile
// RUN step after `dotnet publish` completes.
//
// It reads the static web assets endpoints manifest (*.staticwebassets.endpoints.json)
// generated by the .NET SDK's GenerateStaticWebAssetEndpointsManifest MSBuild target
// (see: https://github.com/dotnet/sdk/blob/main/src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets)
// and consumed by ASP.NET Core's MapStaticAssets() endpoint routing middleware
// (see: https://github.com/dotnet/aspnetcore/blob/main/src/StaticAssets/src/StaticAssetEndpointRouteBuilderExtensions.cs).
//
// The script prefixes every AssetFile path with the app's URL segment so the gateway
// can serve multiple WASM apps under distinct path prefixes, and adds a SPA catch-all
// fallback endpoint cloned from index.html.
//
// Usage: dotnet run PrefixEndpoints.cs -- <manifest-path> <prefix> <output-path>

using System.Globalization;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;

if (args.Length < 3)
{
    Console.Error.WriteLine("Usage: dotnet run PrefixEndpoints.cs -- <manifest-path> <prefix> <output-path>");
    return 1;
}

var manifestPath = args[0];
var prefix = args[1];
var outputPath = args[2];

var manifest = JsonSerializer.Deserialize(
    File.ReadAllText(manifestPath),
    ManifestJsonContext.Default.EndpointsManifest)!;

var sourceEndpoints = manifest.Endpoints;
manifest.Endpoints = sourceEndpoints
    .Where(endpoint => !IsSpaFallbackEndpoint(endpoint, sourceEndpoints))
    .ToArray();

var fallbackEndpoints = new List<EndpointEntry>();

foreach (var ep in manifest.Endpoints)
{
    ep.AssetFile = $"{prefix}/{ep.AssetFile}";

    // Clone only the identity (uncompressed) index.html endpoint as a catch-all SPA fallback.
    // Skip compressed variants (those with Content-Encoding selectors) because the
    // ContentEncodingNegotiationMatcherPolicy would otherwise prefer the catch-all over
    // literal routes (like _blazor/_configuration) that lack encoding metadata.
    if (ep.Route == "index.html")
    {
        var hasContentEncoding = ep.Selectors?.Any(s => s.Name == "Content-Encoding") == true;

        if (!hasContentEncoding)
        {
            // Deep-clone via round-trip serialization, then patch route and cache header
            var fallbackJson = JsonSerializer.Serialize(ep, ManifestJsonContext.Default.EndpointEntry);
            var fallback = JsonSerializer.Deserialize(fallbackJson, ManifestJsonContext.Default.EndpointEntry)!;
            fallback.Route = "{**fallback:nonfile}";
            fallback.ExtensionData ??= [];
            fallback.ExtensionData["Order"] = JsonSerializer.SerializeToElement(
                int.MaxValue.ToString(CultureInfo.InvariantCulture),
                ManifestJsonContext.Default.String);
            if (fallback.ResponseHeaders is not null)
            {
                foreach (var header in fallback.ResponseHeaders)
                {
                    if (header.Name == "Cache-Control")
                    {
                        header.Value = "no-store";
                    }
                }
            }
            fallbackEndpoints.Add(fallback);
        }
    }
}

manifest.Endpoints = [.. manifest.Endpoints, .. fallbackEndpoints];

var dir = Path.GetDirectoryName(outputPath);
if (dir is not null)
{
    Directory.CreateDirectory(dir);
}

File.WriteAllText(outputPath, JsonSerializer.Serialize(manifest, ManifestJsonContext.Relaxed.EndpointsManifest));

return 0;

static bool IsSpaFallbackEndpoint(EndpointEntry endpoint, EndpointEntry[] endpoints)
{
    // .NET 11 doesn't add explicit fallback metadata, so recognize the SDK/legacy shape by
    // combining the nonfile catch-all route with an index.html asset.
    return endpoint.ExtensionData?.TryGetValue("Order", out var order) == true
        && order.ValueKind == JsonValueKind.String
        && order.GetString() == int.MaxValue.ToString(CultureInfo.InvariantCulture)
        && endpoint.Route.StartsWith("{**", StringComparison.Ordinal)
        && endpoint.Route.EndsWith(":nonfile}", StringComparison.Ordinal)
        && endpoints.Any(indexEndpoint =>
            string.Equals(indexEndpoint.Route, "index.html", StringComparison.OrdinalIgnoreCase)
            && string.Equals(indexEndpoint.AssetFile, endpoint.AssetFile, StringComparison.Ordinal));
}

// Same typed model used by the Hosting library's EndpointsManifestTransformer
class EndpointsManifest
{
    public EndpointEntry[] Endpoints { get; set; } = [];

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }
}

class EndpointEntry
{
    public string Route { get; set; } = "";
    public string AssetFile { get; set; } = "";
    public EndpointSelector[]? Selectors { get; set; }
    public EndpointResponseHeader[]? ResponseHeaders { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }
}

class EndpointSelector
{
    public string Name { get; set; } = "";

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }
}

class EndpointResponseHeader
{
    public string Name { get; set; } = "";
    public string Value { get; set; } = "";

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }
}

[JsonSerializable(typeof(EndpointsManifest))]
[JsonSerializable(typeof(EndpointEntry))]
[JsonSerializable(typeof(string))]
[JsonSourceGenerationOptions(
    WriteIndented = true)]
partial class ManifestJsonContext : JsonSerializerContext
{
    internal static ManifestJsonContext Relaxed { get; } = new(new JsonSerializerOptions
    {
        WriteIndented = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    });
}
